name: CI

on:
  push:
    branches: ["main", "work"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Run CI script
        run: ./scripts/hello.sh
      - name: Build React app
        working-directory: frontend
        run: npm run build
